### ISSUE TITLE
Not working on Meteor 1.2.1

### ISSUE THREAD

**Issue by rpesciotta** [sergeyt/meteor-typeahead#144]
Hi,

I'm using meteor 1.2.1, and tried all the different examples with a newly created app (default meteor create app), and none of them work. I noticed that the helpers (linked to the data-source prop) is never triggered.
Is there any version-related issue here?

**Comment by sergeyt** [comment]
@rpesciotta the reason is usage of internal meteor functions by this package. Hope this should be easy to fix having ready environment with just debugger (and BTW I don't have such environment now). So as usual please feel free to make PR fixing this issue. Also it is fine to fix with breaking changes for previous meteor versions, and maybe start following semantic versioning rules.

**Comment by lucatros** [comment]
@rpesciotta Did you find any workaround to make it work on 1.2.1?

**Comment by lucatros** [comment]
I ended up using the following code until the helper is fixed:

```javascript
Template.templateName.onRendered(() => {
  Meteor.typeahead.inject();

  $('.typeahead').on('typeahead:selected', function(evt, suggestion) {
    console.log(suggestion.id); 
    console.log(suggestion.value); 
  });
});

```

**Comment by rpesciotta** [comment]
@sergeyt: I'm willing for file a PR, but I'm going through some basics about version dependencies, and how the package actually works. So far no luck...
@lucatros: found no workaround yet.

I will try the workaround from @lucatros for the moment and see if I can at least get it to work.

**Comment by sergeyt** [comment]
@rpesciotta I've just checked that demo app (inside this repository) is still working without any changes in the package code on latest meteor 1.3.
