### ISSUE TITLE
typeahead fails if form element inside conditional block

### ISSUE THREAD

**Issue by DanAncona** [sergeyt/meteor-typeahead#58]
Hi there - took me a painful amount of time to track this down but it seems like typeahead fails if it's inside a conditional block. I had part of a template inside `{{#if currentUser}}` and eventually (after trying everything else under the sun) realized it seems to be any conditional that causes it to fail. I.e. using the basic example, putting this in the template - 

```html
{{#if 1}}
<input class="form-control typeahead" name="team" type="text"
       placeholder="NBA teams"
       autocomplete="off" spellcheck="off"
       data-source="nba"/>
{{/if}}
```
makes it nonfunctional. Sometimes it fails silently, sometimes I get "Unable to resolve data source function 'nba'." and I'm not sure what yet causes that, but hope this is enough to track it down. Thanks.

**Comment by sergeyt** [comment]
@DanAncona as workaround try to always put typeahead input into separate template. The problem is that the package at least try to resolve `data-source` function from current template context and it seems it is not working in conditional blocks. Also there should be an API to pass `data-source` and other options explicitly to `Meteor.typeahead` activation function.

Also descriptive warning messages (enabled somehow only for development environment) could help to figure out with these "meteor reflection" issues.

I need to find a time to debug if there is a way to resolve functions from any meteor template context.

**Comment by benmgreene** [comment]
This may actually be due to a Meteor-related bug.  See below:

Fix bug where, when a helper or event handler was called from inside a custom block helper, `Template.instance()` returned the `Template.contentBlock` template instead of the actual user-defined template, making it difficult to use `Template.instance()` for local template state.

Source: https://github.com/meteor/meteor/blob/devel/History.md#vnext

**Comment by taylordj** [comment]
Can confirm the same issue when using inside an {{#each}} block, putting Typeahead's input inside its own template does not seem to help. I'm going to start debugging.
